/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/log/file_task_handler.py:187 ResourceWarning: unclosed file <_io.TextIOWrapper name='/opt/airflow/logs/dag_id=spark_tracing_example/run_id=manual__2024-12-07T23:42:24.106393+00:00/task_id=spark_task/attempt=1.log' mode='a' encoding='utf-8'>
[2024-12-07T23:42:40.414+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_tracing_example.spark_task manual__2024-12-07T23:42:24.106393+00:00 [queued]>
[2024-12-07T23:42:40.423+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_tracing_example.spark_task manual__2024-12-07T23:42:24.106393+00:00 [queued]>
[2024-12-07T23:42:40.424+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-12-07T23:42:40.442+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): spark_task> on 2024-12-07 23:42:24.106393+00:00
[2024-12-07T23:42:40.446+0000] {standard_task_runner.py:57} INFO - Started process 154 to run task
[2024-12-07T23:42:40.451+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'spark_tracing_example', 'spark_task', 'manual__2024-12-07T23:42:24.106393+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/tracing_dag.py', '--cfg-path', '/tmp/tmprqaex79_']
[2024-12-07T23:42:40.452+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask spark_task
[2024-12-07T23:42:40.502+0000] {task_command.py:410} INFO - Running <TaskInstance: spark_tracing_example.spark_task manual__2024-12-07T23:42:24.106393+00:00 [running]> on host e219fcd911b9
[2024-12-07T23:42:40.701+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='spark_tracing_example' AIRFLOW_CTX_TASK_ID='spark_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T23:42:24.106393+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-07T23:42:24.106393+00:00'
[2024-12-07T23:42:40.706+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2024-12-07T23:42:40.708+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master local[*] --conf spark.master=local[*] --conf spark.submit.deployMode=client --name arrow-spark --queue root.default /opt/airflow/spark_job.py
[2024-12-07T23:42:43.298+0000] {spark_submit.py:490} INFO - /usr/local/bin/python3: can't find '__main__' module in '/opt/airflow/spark_job.py/'
[2024-12-07T23:42:43.324+0000] {spark_submit.py:490} INFO - 24/12/07 23:42:43 INFO ShutdownHookManager: Shutdown hook called
[2024-12-07T23:42:43.328+0000] {spark_submit.py:490} INFO - 24/12/07 23:42:43 INFO ShutdownHookManager: Deleting directory /tmp/spark-ff150df6-5343-4621-a96c-23e6697996aa
[2024-12-07T23:42:43.374+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master local[*] --conf spark.master=local[*] --conf spark.submit.deployMode=client --name arrow-spark --queue root.default /opt/airflow/spark_job.py. Error code is: 1.
[2024-12-07T23:42:43.379+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=spark_tracing_example, task_id=spark_task, execution_date=20241207T234224, start_date=20241207T234240, end_date=20241207T234243
[2024-12-07T23:42:43.393+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 7 for task spark_task (Cannot execute: spark-submit --master local[*] --conf spark.master=local[*] --conf spark.submit.deployMode=client --name arrow-spark --queue root.default /opt/airflow/spark_job.py. Error code is: 1.; 154)
[2024-12-07T23:42:43.413+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-07T23:42:43.431+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
