/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/log/file_task_handler.py:187 ResourceWarning: unclosed file <_io.TextIOWrapper name='/opt/airflow/logs/dag_id=spark_tracing_example/run_id=manual__2024-12-07T22:42:48.951238+00:00/task_id=spark_task/attempt=1.log' mode='a' encoding='utf-8'>
[2024-12-07T22:43:05.914+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_tracing_example.spark_task manual__2024-12-07T22:42:48.951238+00:00 [queued]>
[2024-12-07T22:43:05.924+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_tracing_example.spark_task manual__2024-12-07T22:42:48.951238+00:00 [queued]>
[2024-12-07T22:43:05.924+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-12-07T22:43:05.943+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): spark_task> on 2024-12-07 22:42:48.951238+00:00
[2024-12-07T22:43:05.947+0000] {standard_task_runner.py:57} INFO - Started process 213 to run task
[2024-12-07T22:43:05.952+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'spark_tracing_example', 'spark_task', 'manual__2024-12-07T22:42:48.951238+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/tracing_dag.py', '--cfg-path', '/tmp/tmp6eqwqhce']
[2024-12-07T22:43:05.954+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask spark_task
[2024-12-07T22:43:06.006+0000] {task_command.py:410} INFO - Running <TaskInstance: spark_tracing_example.spark_task manual__2024-12-07T22:42:48.951238+00:00 [running]> on host a824517f02e6
[2024-12-07T22:43:06.218+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='spark_tracing_example' AIRFLOW_CTX_TASK_ID='spark_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T22:42:48.951238+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-07T22:42:48.951238+00:00'
[2024-12-07T22:43:06.225+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2024-12-07T22:43:06.226+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark --queue root.default /opt/airflow/spark_job.py
[2024-12-07T22:43:06.373+0000] {spark_submit.py:490} INFO - /home/airflow/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-12-07T22:43:06.374+0000] {spark_submit.py:490} INFO - JAVA_HOME is not set
[2024-12-07T22:43:06.385+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark --queue root.default /opt/airflow/spark_job.py. Error code is: 1.
[2024-12-07T22:43:06.390+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=spark_tracing_example, task_id=spark_task, execution_date=20241207T224248, start_date=20241207T224305, end_date=20241207T224306
[2024-12-07T22:43:06.403+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 10 for task spark_task (Cannot execute: spark-submit --master yarn --name arrow-spark --queue root.default /opt/airflow/spark_job.py. Error code is: 1.; 213)
[2024-12-07T22:43:06.419+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-07T22:43:06.439+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
