/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/log/file_task_handler.py:187 ResourceWarning: unclosed file <_io.TextIOWrapper name='/opt/airflow/logs/dag_id=spark_tracing_example/run_id=manual__2024-12-07T22:08:36.215008+00:00/task_id=spark_task/attempt=1.log' mode='a' encoding='utf-8'>
[2024-12-07T22:08:52.098+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_tracing_example.spark_task manual__2024-12-07T22:08:36.215008+00:00 [queued]>
[2024-12-07T22:08:52.108+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_tracing_example.spark_task manual__2024-12-07T22:08:36.215008+00:00 [queued]>
[2024-12-07T22:08:52.108+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-12-07T22:08:52.125+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): spark_task> on 2024-12-07 22:08:36.215008+00:00
[2024-12-07T22:08:52.129+0000] {standard_task_runner.py:57} INFO - Started process 113 to run task
[2024-12-07T22:08:52.134+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'spark_tracing_example', 'spark_task', 'manual__2024-12-07T22:08:36.215008+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/tracing_dag.py', '--cfg-path', '/tmp/tmp65dqdjjw']
[2024-12-07T22:08:52.135+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask spark_task
[2024-12-07T22:08:52.190+0000] {task_command.py:410} INFO - Running <TaskInstance: spark_tracing_example.spark_task manual__2024-12-07T22:08:36.215008+00:00 [running]> on host b2b1d0efbb19
[2024-12-07T22:08:52.394+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='spark_tracing_example' AIRFLOW_CTX_TASK_ID='spark_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T22:08:36.215008+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-07T22:08:36.215008+00:00'
[2024-12-07T22:08:52.400+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2024-12-07T22:08:52.402+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark --queue root.default /opt/airflow/spark_job.py
[2024-12-07T22:08:52.534+0000] {spark_submit.py:490} INFO - /home/airflow/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-12-07T22:08:52.535+0000] {spark_submit.py:490} INFO - JAVA_HOME is not set
[2024-12-07T22:08:52.545+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark --queue root.default /opt/airflow/spark_job.py. Error code is: 1.
[2024-12-07T22:08:52.549+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=spark_tracing_example, task_id=spark_task, execution_date=20241207T220836, start_date=20241207T220852, end_date=20241207T220852
[2024-12-07T22:08:52.562+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 7 for task spark_task (Cannot execute: spark-submit --master yarn --name arrow-spark --queue root.default /opt/airflow/spark_job.py. Error code is: 1.; 113)
[2024-12-07T22:08:52.600+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-07T22:08:52.620+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
